# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-11-19 08:43+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../apport/ui.py:124
msgid "This package does not seem to be installed correctly"
msgstr ""

#: ../apport/ui.py:128
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""

#: ../apport/ui.py:145
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:251
msgid "unknown program"
msgstr ""

#: ../apport/ui.py:252
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr ""

#: ../apport/ui.py:254 ../apport/ui.py:1255
#, python-format
msgid "Problem in %s"
msgstr ""

#: ../apport/ui.py:255
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""

#. package does not exist
#: ../apport/ui.py:270 ../apport/ui.py:276 ../apport/ui.py:282
#: ../apport/ui.py:320 ../apport/ui.py:328 ../apport/ui.py:455
#: ../apport/ui.py:458 ../apport/ui.py:659 ../apport/ui.py:1086
#: ../apport/ui.py:1227 ../apport/ui.py:1231
msgid "Invalid problem report"
msgstr ""

#: ../apport/ui.py:271 ../apport/ui.py:1233
msgid "This problem report is damaged and cannot be processed."
msgstr ""

#: ../apport/ui.py:277
msgid "The report belongs to a package that is not installed."
msgstr ""

#: ../apport/ui.py:283
msgid "An error occurred while attempting to process this problem report:"
msgstr ""

#: ../apport/ui.py:321
msgid "You are not allowed to access this problem report."
msgstr ""

#: ../apport/ui.py:324
msgid "Error"
msgstr ""

#: ../apport/ui.py:325
msgid "There is not enough disk space available to process this report."
msgstr ""

#: ../apport/ui.py:409
msgid "No package specified"
msgstr ""

#: ../apport/ui.py:410
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:433
msgid "Permission denied"
msgstr ""

#: ../apport/ui.py:434
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""

#: ../apport/ui.py:436
msgid "Invalid PID"
msgstr ""

#: ../apport/ui.py:437
msgid "The specified process ID does not belong to a program."
msgstr ""

#: ../apport/ui.py:456
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr ""

#: ../apport/ui.py:459
#, python-format
msgid "Package %s does not exist"
msgstr ""

#: ../apport/ui.py:483 ../apport/ui.py:671 ../apport/ui.py:676
msgid "Cannot create report"
msgstr ""

#: ../apport/ui.py:498 ../apport/ui.py:544 ../apport/ui.py:561
msgid "Updating problem report"
msgstr ""

#: ../apport/ui.py:499
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""

#: ../apport/ui.py:508
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-bug"
"\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""

#: ../apport/ui.py:545 ../apport/ui.py:562
msgid "No additional information collected."
msgstr ""

#: ../apport/ui.py:613
msgid "What kind of problem do you want to report?"
msgstr ""

#: ../apport/ui.py:630
msgid "Unknown symptom"
msgstr ""

#: ../apport/ui.py:631
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr ""

#: ../apport/ui.py:662
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""

#: ../apport/ui.py:672 ../apport/ui.py:677
msgid "xprop failed to determine process ID of the window"
msgstr ""

#: ../apport/ui.py:691
msgid "%prog <report number>"
msgstr ""

#: ../apport/ui.py:693
msgid "Specify package name."
msgstr ""

#: ../apport/ui.py:695 ../apport/ui.py:746
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""

#: ../apport/ui.py:725
msgid "%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../apport/ui.py:728
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""

#: ../apport/ui.py:730
msgid "Click a window as a target for filing a problem report."
msgstr ""

#: ../apport/ui.py:732
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""

#: ../apport/ui.py:734
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:736
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""

#: ../apport/ui.py:738
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""

#: ../apport/ui.py:740
msgid "The provided pid is a hanging application."
msgstr ""

#: ../apport/ui.py:742
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""

#: ../apport/ui.py:744
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""

#: ../apport/ui.py:748
msgid "Print the Apport version number."
msgstr ""

#: ../apport/ui.py:888
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""

#: ../apport/ui.py:889
msgid "Run gdb session"
msgstr ""

#: ../apport/ui.py:890
msgid "Run gdb session without downloading debug symbols"
msgstr ""

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:892
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr ""

#: ../apport/ui.py:965 ../apport/ui.py:975
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""

#: ../apport/ui.py:989
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""

#: ../apport/ui.py:1087
msgid "Could not determine the package or source package name."
msgstr ""

#: ../apport/ui.py:1105
msgid "Unable to start web browser"
msgstr ""

#: ../apport/ui.py:1106
#, python-format
msgid "Unable to start web browser to open %s."
msgstr ""

#: ../apport/ui.py:1181
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""

#: ../apport/ui.py:1193
msgid "Network problem"
msgstr ""

#: ../apport/ui.py:1195
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""

#: ../apport/ui.py:1222
msgid "Memory exhaustion"
msgstr ""

#: ../apport/ui.py:1223
msgid "Your system does not have enough memory to process this crash report."
msgstr ""

#: ../apport/ui.py:1258
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:1314 ../apport/ui.py:1321
msgid "Problem already known"
msgstr ""

#: ../apport/ui.py:1315
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""

#: ../apport/ui.py:1322
msgid "This problem was already reported to developers. Thank you!"
msgstr ""

#: ../bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr ""

#: ../bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr ""

#: ../bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr ""

#: ../bin/apport-cli.py:145
#, python-format
msgid "(%i bytes)"
msgstr ""

#: ../bin/apport-cli.py:147 ../gtk/apport-gtk.py:138 ../kde/apport-kde.py:338
msgid "(binary data)"
msgstr ""

#: ../bin/apport-cli.py:175 ../gtk/apport-gtk.py:173 ../kde/apport-kde.py:162
msgid "Send problem report to the developers?"
msgstr ""

#: ../bin/apport-cli.py:176
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""

#: ../bin/apport-cli.py:179
#, python-format
msgid "&Send report (%s)"
msgstr ""

#: ../bin/apport-cli.py:183
msgid "&Examine locally"
msgstr ""

#: ../bin/apport-cli.py:187
msgid "&View report"
msgstr ""

#: ../bin/apport-cli.py:188
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""

#: ../bin/apport-cli.py:189
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""

#: ../bin/apport-cli.py:191 ../bin/apport-cli.py:268 ../bin/apport-cli.py:300
#: ../bin/apport-cli.py:321
msgid "&Cancel"
msgstr ""

#: ../bin/apport-cli.py:219
msgid "Problem report file:"
msgstr ""

#: ../bin/apport-cli.py:225 ../bin/apport-cli.py:230
msgid "&Confirm"
msgstr ""

#: ../bin/apport-cli.py:229
#, python-format
msgid "Error: %s"
msgstr ""

#: ../bin/apport-cli.py:235 ../kde/apport-kde.py:383
msgid "Collecting problem information"
msgstr ""

#: ../bin/apport-cli.py:236
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""

#: ../bin/apport-cli.py:248 ../kde/apport-kde.py:411 ../gtk/apport-gtk.ui.h:13
msgid "Uploading problem information"
msgstr ""

#: ../bin/apport-cli.py:249
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""

#: ../bin/apport-cli.py:299
msgid "&Done"
msgstr ""

#: ../bin/apport-cli.py:305
msgid "none"
msgstr ""

#: ../bin/apport-cli.py:306
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr ""

#: ../bin/apport-cli.py:322
msgid "Choices:"
msgstr ""

#: ../bin/apport-cli.py:336
msgid "Path to file (Enter to cancel):"
msgstr ""

#: ../bin/apport-cli.py:342
msgid "File does not exist."
msgstr ""

#: ../bin/apport-cli.py:344
msgid "This is a directory."
msgstr ""

#: ../bin/apport-cli.py:350
msgid "To continue, you must visit the following URL:"
msgstr ""

#: ../bin/apport-cli.py:352
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""

#: ../bin/apport-cli.py:354
msgid "Launch a browser now"
msgstr ""

#: ../bin/apport-cli.py:368
msgid "No pending crash reports. Try --help for more information."
msgstr ""

#: ../data/apportcheckresume.py:68
msgid ""
"This occured during a previous suspend and prevented it from resuming "
"properly."
msgstr ""

#: ../data/apportcheckresume.py:70
msgid ""
"This occured during a previous hibernate and prevented it from resuming "
"properly."
msgstr ""

#: ../data/apportcheckresume.py:75
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""

#: ../bin/apport-retrace.py:31
msgid "%prog [options] <apport problem report | crash ID>"
msgstr ""

#: ../bin/apport-retrace.py:33
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""

#: ../bin/apport-retrace.py:35
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""

#: ../bin/apport-retrace.py:37
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""

#: ../bin/apport-retrace.py:39
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""

#: ../bin/apport-retrace.py:41
msgid "Override report's CoreFile"
msgstr ""

#: ../bin/apport-retrace.py:43
msgid "Override report's ExecutablePath"
msgstr ""

#: ../bin/apport-retrace.py:45
msgid "Override report's ProcMaps"
msgstr ""

#: ../bin/apport-retrace.py:47
msgid "Rebuild report's Package information"
msgstr ""

#: ../bin/apport-retrace.py:49
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""

#: ../bin/apport-retrace.py:51
msgid "Report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-retrace.py:53
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""

#: ../bin/apport-retrace.py:55
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""

#: ../bin/apport-retrace.py:57
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""

#: ../bin/apport-retrace.py:59 ../bin/apport-valgrind.py:66
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""

#: ../bin/apport-retrace.py:61
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""

#: ../bin/apport-retrace.py:63
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""

#: ../bin/apport-retrace.py:65
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""

#: ../bin/apport-retrace.py:70
msgid "incorrect number of arguments; use --help for a short help"
msgstr ""

#: ../bin/apport-retrace.py:76
msgid "You cannot use -C without -S. Stopping."
msgstr ""

#: ../bin/apport-retrace.py:80
msgid ""
"you either need to do a local operation (-s, -g, -o) or supply an "
"authentication file (--auth); see --help for a short help"
msgstr ""

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:114
msgid "OK to send these as attachments? [y/n]"
msgstr ""

#: ../kde/apport-kde.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr ""

#: ../kde/apport-kde.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr ""

#: ../data/kernel_oops.py:28
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""

#: ../gtk/apport-gtk.py:153
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:156
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:161 ../kde/apport-kde.py:176 ../kde/apport-kde.py:217
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr ""

#: ../gtk/apport-gtk.py:182 ../kde/apport-kde.py:170
msgid "Send"
msgstr ""

#: ../gtk/apport-gtk.py:200 ../gtk/apport-gtk.py:569 ../kde/apport-kde.py:271
#: ../gtk/apport-gtk.ui.h:7
msgid "Show Details"
msgstr ""

#: ../gtk/apport-gtk.py:212 ../gtk/apport-gtk.py:280 ../gtk/apport-gtk.py:299
#: ../kde/apport-kde.py:210 ../kde/apport-kde.py:223 ../gtk/apport-gtk.ui.h:10
msgid "Continue"
msgstr ""

#: ../gtk/apport-gtk.py:224
msgid "Force Closed"
msgstr ""

#: ../gtk/apport-gtk.py:225 ../gtk/apport-gtk.py:284 ../kde/apport-kde.py:214
#: ../kde/apport-kde.py:357
msgid "Relaunch"
msgstr ""

#: ../gtk/apport-gtk.py:234
#, python-format
msgid "The application %s has stopped responding."
msgstr ""

#: ../gtk/apport-gtk.py:238
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr ""

#: ../gtk/apport-gtk.py:253 ../kde/apport-kde.py:184
#, python-format
msgid "Package: %s"
msgstr ""

#: ../gtk/apport-gtk.py:260 ../kde/apport-kde.py:190
msgid "Sorry, a problem occurred while installing software."
msgstr ""

#: ../gtk/apport-gtk.py:269 ../gtk/apport-gtk.py:288 ../kde/apport-kde.py:197
#, python-format
msgid "The application %s has experienced an internal error."
msgstr ""

#: ../gtk/apport-gtk.py:272 ../kde/apport-kde.py:201
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr ""

#: ../gtk/apport-gtk.py:283 ../kde/apport-kde.py:213 ../gtk/apport-gtk.ui.h:9
msgid "Leave Closed"
msgstr ""

#: ../gtk/apport-gtk.py:296 ../kde/apport-kde.py:220 ../gtk/apport-gtk.ui.h:4
msgid "If you notice further problems, try restarting the computer."
msgstr ""

#: ../gtk/apport-gtk.py:300 ../kde/apport-kde.py:224
msgid "Ignore future problems of this type"
msgstr ""

#: ../gtk/apport-gtk.py:573 ../kde/apport-kde.py:268
msgid "Hide Details"
msgstr ""

#: ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr ""

#: ../bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr ""

#: ../bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""

#: ../bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""

#: ../bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""

#: ../bin/apport-valgrind.py:58
msgid "report download/install progress when installing packages into sandbox"
msgstr ""

#: ../bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr ""

#: ../kde/apport-kde.py:294
msgid "Username:"
msgstr ""

#: ../kde/apport-kde.py:295
msgid "Password:"
msgstr ""

#: ../kde/apport-kde.py:382
msgid "Collecting Problem Information"
msgstr ""

#: ../kde/apport-kde.py:384
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""

#: ../kde/apport-kde.py:410
msgid "Uploading Problem Information"
msgstr ""

#: ../kde/apport-kde.py:412 ../gtk/apport-gtk.ui.h:15
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""

#: ../kde/apport-kde.py:446 ../kde/apport-kde.py:482 ../gtk/apport-gtk.ui.h:1
msgid "Apport"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr ""

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr ""

#: ../gtk/apport-gtk.ui.h:2
msgid "Crash report"
msgstr ""

#: ../gtk/apport-gtk.ui.h:3
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:5
msgid "Send an error report to help fix this problem"
msgstr ""

#: ../gtk/apport-gtk.ui.h:6
msgid "Ignore future problems of this program version"
msgstr ""

#: ../gtk/apport-gtk.ui.h:8
msgid "_Examine locally"
msgstr ""

#: ../gtk/apport-gtk.ui.h:11
msgid "<big><b>Collecting problem information</b></big>"
msgstr ""

#: ../gtk/apport-gtk.ui.h:12
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""

#: ../gtk/apport-gtk.ui.h:14
msgid "<big><b>Uploading problem information</b></big>"
msgstr ""

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr ""

#: ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr ""

#: ../bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr ""
